theme: jekyll-theme-cayman
title: Les Recettes de Beunoua
description: Les recettes que c'est celles que j'aime bien
github:
  is_project_page: False

collections:
  recettes:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "recettes"
    values:
      layout: default
  
exclude: [
  Gemfile,
  Gemfile.lock,
  index.md,
  Makefile,
  README.md,
  update_index.py
]